### ISSUE TITLE
[build] Fail to build on Ubuntu 22.04

### ISSUE THREAD

**Issue by yukkysaito** [raysan5/raylib#3671]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description
I'm trying to build using cmake according to [these instructions](https://github.com/raysan5/raylib/wiki/Working-on-GNU-Linux#build-raylib-using-cmake). In my environment, the following error occurs. Is there anyone else who has encountered a similar error?

BTW, I was able to build successfully with the [released version 5.0](https://github.com/raysan5/raylib/releases/tag/5.0).

```
Consolidate compiler generated dependencies of target rlgl_compute_shader
[ 49%] Built target rlgl_compute_shader
Consolidate compiler generated dependencies of target rlgl_standalone
[ 49%] Linking C executable rlgl_standalone
/usr/bin/ld: CMakeFiles/rlgl_standalone.dir/others/rlgl_standalone.c.o: in function `main':
/home/yukky/workspace/raylib/examples/others/rlgl_standalone.c:125: undefined reference to `glfwSetErrorCallback'
/usr/bin/ld: /home/yukky/workspace/raylib/examples/others/rlgl_standalone.c:127: undefined reference to `glfwInit'
/usr/bin/ld: /home/yukky/workspace/raylib/examples/others/rlgl_standalone.c:134: undefined reference to `glfwWindowHint'
/usr/bin/ld: /home/yukky/workspace/raylib/examples/others/rlgl_standalone.c:135: undefined reference to `glfwWindowHint'
/usr/bin/ld: /home/yukky/workspace/raylib/examples/others/rlgl_standalone.c:138: undefined reference to `glfwWindowHint'
/usr/bin/ld: /home/yukky/workspace/raylib/examples/others/rlgl_standalone.c:139: undefined reference to `glfwWindowHint'
/usr/bin/ld: /home/yukky/workspace/raylib/examples/others/rlgl_standalone.c:140: undefined reference to `glfwWindowHint'
/usr/bin/ld: /home/yukky/workspace/raylib/examples/others/rlgl_standalone.c:146: undefined reference to `glfwCreateWindow'
/usr/bin/ld: /home/yukky/workspace/raylib/examples/others/rlgl_standalone.c:150: undefined reference to `glfwTerminate'
/usr/bin/ld: /home/yukky/workspace/raylib/examples/others/rlgl_standalone.c:155: undefined reference to `glfwSetWindowPos'
/usr/bin/ld: /home/yukky/workspace/raylib/examples/others/rlgl_standalone.c:157: undefined reference to `glfwSetKeyCallback'
/usr/bin/ld: /home/yukky/workspace/raylib/examples/others/rlgl_standalone.c:159: undefined reference to `glfwMakeContextCurrent'
/usr/bin/ld: /home/yukky/workspace/raylib/examples/others/rlgl_standalone.c:160: undefined reference to `glfwSwapInterval'
/usr/bin/ld: /home/yukky/workspace/raylib/examples/others/rlgl_standalone.c:163: undefined reference to `glfwGetProcAddress'
/usr/bin/ld: /home/yukky/workspace/raylib/examples/others/rlgl_standalone.c:242: undefined reference to `glfwSwapBuffers'
/usr/bin/ld: /home/yukky/workspace/raylib/examples/others/rlgl_standalone.c:243: undefined reference to `glfwPollEvents'
/usr/bin/ld: /home/yukky/workspace/raylib/examples/others/rlgl_standalone.c:190: undefined reference to `glfwWindowShouldClose'
/usr/bin/ld: /home/yukky/workspace/raylib/examples/others/rlgl_standalone.c:251: undefined reference to `glfwDestroyWindow'
/usr/bin/ld: /home/yukky/workspace/raylib/examples/others/rlgl_standalone.c:252: undefined reference to `glfwTerminate'
/usr/bin/ld: CMakeFiles/rlgl_standalone.dir/others/rlgl_standalone.c.o: in function `KeyCallback':
/home/yukky/workspace/raylib/examples/others/rlgl_standalone.c:273: undefined reference to `glfwSetWindowShouldClose'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/CMakeFiles/rlgl_standalone.dir/build.make:103: examples/rlgl_standalone] Error 1
make[1]: *** [CMakeFiles/Makefile2:2300: examples/CMakeFiles/rlgl_standalone.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

### Environment

*Provide your Platform, Operating System, OpenGL version, GPU details where you experienced the issue.*
- OS : Ubuntu 22.04.3 LTS
  - Linux Kernel : 6.2.0-39-generic
- Memory : 32.0 GiB
- CPU : Ryzen 9 5900x
- GPU : 1080 Ti
  - CUDA : cuda 11.6
  - Nvidia Driver : 530.30.02
- OpenGL : 4.6.0 NVIDIA 530.30.02
- raylib commit hash ID(latest) : 36df9c5bd6999d5a047cf94097f258a27aaafc52
### Issue Screenshot
![image](https://github.com/raysan5/raylib/assets/8327598/3d6188be-ba65-41d9-800a-7c7bfc8d10a4)

![image](https://github.com/raysan5/raylib/assets/8327598/5feba113-6030-4508-a3d1-2751fb6004a9)

**Comment by raysan5** [comment]
@yukkysaito thanks for reporting. The example `rlgl_standalone` requires linking with GLFW, for some reason it is not linked.

I'm afraid I'm not the maintainer of the CMake build system, contributed by some users. Let's see if some expert could review this issue.

**Comment by dertseha** [comment]
Hi, @yukkysaito  - I'm not a maintainer of the CMake build system, I only poked around a little. (My poking may also help someone with more in-depth knowledge what is up).

Short:
Please try the same build procedure with a different setting of `USE_SHARED_LIBS=ON` -- so, `cmake -DUSE_SHARED_LIBS=OFF ..` as the first command of your screenshots. (or, just `cmake ..`, as I believe `OFF` is the default.)

Long:
Judging by one of the main CMake file `GlfwImport.cmake`, when "shared library" mode is on, it explicitly hides the symbols for dependents (see [source here](https://github.com/raysan5/raylib/blob/master/cmake/GlfwImport.cmake#L26-L28)). 
I suspect this is meant to avoid someone having access to GLFW features directly, just by depending on raylib.so/.dll .

The `rlgl_standalone` example is the only one which wants something from glfw directly, and I believe that this symbold-hiding is the reason for it not being available for just this example.
Assuming that the symbol hiding is intentional (and I'm for that behaviour), I guess that the CMake file for the examples needs some extra handling, at least for the one case to explicitly add a glfw dependency to be visible to the main file.

Again: This is a semi-quick guess by going through the respective sources just online and I might be completely wrong. I'm intending to give people some quick-starts - even if it only helps to find wrong paths quicker :)

**Comment by Peter0x44** [comment]
I implemented the symbol hiding. It's also a problem with the Makefile, it only worked before on "accident" *because* the so did not hide any symbols. Windows DLLs never worked with this example.
I'm not sure how to sort it out. Perhaps disabling building this example would work, or adding a manual "link" to the object library of glfw will sort it out.

**Comment by Peter0x44** [comment]
Also: you can disable building of the examples, pass `-DBUILD_EXAMPLES=No` on your cmake command line
You don't actually need to care about them.

**Comment by statisch** [comment]
I was getting the exact same error and fixed it with @Peter0x44's solution by enabling the cmake flag `-DBUILD_EXAMPLES=NO`. But this option isn't listed [here](https://github.com/raysan5/raylib/wiki/CMake-Build-Options), is it deprecated or just not documented?

**Comment by raysan5** [comment]
Probably `rlgl_standalone` example shouldn't be processed by CMake, any expert with the build system should review it. I'm closing this issue.

**Comment by Peter0x44** [comment]
@raysan5 the example failing to build is a problem with the makefile too, but you have to use LIBTYPE_SHARED to notice it

**Comment by raysan5** [comment]
> @raysan5 the example failing to build is a problem with the makefile too, but you have to use LIBTYPE_SHARED to notice it

@Peter0x44 Please, could you elaborate? I maintain the Makefiles and afaik, they worked.

**Comment by Peter0x44** [comment]
@raysan5 do the following:
```sh
cd src
make clean
make RAYLIB_LIBTYPE=SHARED
cd ../examples
make RAYLIB_LIBTYPE=SHARED
```
and the rlgl_standalone.c example will fail to link in exactly the same manner
