### ISSUE TITLE
android/asset_manager.h not found when compiling for android

### ISSUE THREAD

**Issue by kewp** [raysan5/raylib#273]
> C:\raylib\raylib\src\android>%ANDROID_NDK_ROOT%\ndk-build
[armeabi] Compile thumb  : raylib <= core.c
In file included from jni/../../rlgl.h:53:0,
                 from jni/../../core.c:46:
jni/../../utils.h:31:75: fatal error: android/asset_manager.h: No such file or directory
     #include <android/asset_manager.h>      // Required for: AAssetManager
                                                                           ^
compilation terminated.
make.exe: *** [obj/local/armeabi/objs/raylib/__/__/core.o] Error 1

ANDROID_NDK_ROOT = C:\Users\Karl\Downloads\android-ndk-r10e

**Comment by kewp** [comment]
Problem solved: You need at least r11 of the ndk.

Should update the docs, which give a link to r10e ! https://github.com/raysan5/raylib/wiki/Compile-for-Android

**Comment by kewp** [comment]
Now I'm getting various compile errors.

> [arm64-v8a] Compile        : raylib <= audio.c
jni/../../audio.c:197:6: error: conflicting types for 'IsAudioDeviceReady'
bool IsAudioDeviceReady(void)
     ^
jni/../../raylib.h:930:12: note: previous declaration is here
RLAPI bool IsAudioDeviceReady(void);                                  // Check if audio device has been initiali...
           ^
jni/../../audio.c:526:6: error: conflicting types for 'IsSoundPlaying'

**Comment by raysan5** [comment]
Hi @kewp, thanks for pointing this issues, just updated docs to latest Android SDK and NDK versions.

Are you using raylib 1.6 (from Windows installer) or [latest develop version](https://github.com/raysan5/raylib/tree/develop)?

I'm working on raylib v1.7, it's almost ready, and I'm changing quite a lot of things, one of the changes is a Android build system, using a standalone toolchain... but still requires some work.

**Comment by kewp** [comment]
Hi raysan. No problem.

Im using version 1.6

**Comment by raysan5** [comment]
ok, I'll try to upload new raylib version in a couple of weeks...

**Comment by kewp** [comment]
Great. Thanks, I'll let you know how it goes. And will keep trying this end.

**Comment by raysan5** [comment]
Just closing this issue for now...
