### ISSUE TITLE
OpenGL ES 2.0 compilation broken

### ISSUE THREAD

**Issue by define-private-public** [raysan5/raylib#337]
This is from working on my `cmake_test` branch is (typically) up to sync with your `develop` branch.  I tried out building raylib with `GRAPHICS_API_OPENGL_ES2` on and got this:

```
[  1%] Building C object release/CMakeFiles/raylib.dir/rlgl.c.o
/home/ben/Projects/raylib/src/rlgl.c: In function ‘GenTextureCubemap’:
/home/ben/Projects/raylib/src/rlgl.c:2518:14: error: ‘GL_TEXTURE_CUBE_MAP_SEAMLESS’ undeclared (first use in this function)
     glEnable(GL_TEXTURE_CUBE_MAP_SEAMLESS);
              ^
/home/ben/Projects/raylib/src/rlgl.c:2518:14: note: each undeclared identifier is reported only once for each function it appears in
/home/ben/Projects/raylib/src/rlgl.c:2526:44: error: ‘GL_DEPTH_COMPONENT24’ undeclared (first use in this function)
     glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH_COMPONENT24, size, size);
                                            ^
/home/ben/Projects/raylib/src/rlgl.c:2534:61: error: ‘GL_RGB16F’ undeclared (first use in this function)
         glTexImage2D(GL_TEXTURE_CUBE_MAP_POSITIVE_X + i, 0, GL_RGB16F, size, size, 0, GL_RGB, GL_FLOAT, NULL);
                                                             ^
/home/ben/Projects/raylib/src/rlgl.c:2537:42: error: ‘GL_TEXTURE_WRAP_R’ undeclared (first use in this function)
     glTexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_WRAP_R, GL_CLAMP_TO_EDGE);
                                          ^
/home/ben/Projects/raylib/src/rlgl.c: In function ‘GenTextureIrradiance’:
/home/ben/Projects/raylib/src/rlgl.c:2599:44: error: ‘GL_DEPTH_COMPONENT24’ undeclared (first use in this function)
     glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH_COMPONENT24, size, size);
                                            ^
/home/ben/Projects/raylib/src/rlgl.c:2606:61: error: ‘GL_RGB16F’ undeclared (first use in this function)
         glTexImage2D(GL_TEXTURE_CUBE_MAP_POSITIVE_X + i, 0, GL_RGB16F, size, size, 0, GL_RGB, GL_FLOAT, NULL);
                                                             ^
/home/ben/Projects/raylib/src/rlgl.c:2609:42: error: ‘GL_TEXTURE_WRAP_R’ undeclared (first use in this function)
     glTexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_WRAP_R, GL_CLAMP_TO_EDGE);
                                          ^
/home/ben/Projects/raylib/src/rlgl.c: In function ‘GenTexturePrefilter’:
/home/ben/Projects/raylib/src/rlgl.c:2672:44: error: ‘GL_DEPTH_COMPONENT24’ undeclared (first use in this function)
     glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH_COMPONENT24, size, size);
                                            ^
/home/ben/Projects/raylib/src/rlgl.c:2679:61: error: ‘GL_RGB16F’ undeclared (first use in this function)
         glTexImage2D(GL_TEXTURE_CUBE_MAP_POSITIVE_X + i, 0, GL_RGB16F, size, size, 0, GL_RGB, GL_FLOAT, NULL);
                                                             ^
/home/ben/Projects/raylib/src/rlgl.c:2682:42: error: ‘GL_TEXTURE_WRAP_R’ undeclared (first use in this function)
     glTexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_WRAP_R, GL_CLAMP_TO_EDGE);
                                          ^
/home/ben/Projects/raylib/src/rlgl.c: In function ‘GenTextureBRDF’:
/home/ben/Projects/raylib/src/rlgl.c:2753:36: error: ‘GL_RG16F’ undeclared (first use in this function)
     glTexImage2D(GL_TEXTURE_2D, 0, GL_RG16F, size, size, 0, GL_RG, GL_FLOAT, 0);
                                    ^
/home/ben/Projects/raylib/src/rlgl.c:2753:61: error: ‘GL_RG’ undeclared (first use in this function)
     glTexImage2D(GL_TEXTURE_2D, 0, GL_RG16F, size, size, 0, GL_RG, GL_FLOAT, 0);
                                                             ^
/home/ben/Projects/raylib/src/rlgl.c:2765:44: error: ‘GL_DEPTH_COMPONENT24’ undeclared (first use in this function)
     glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH_COMPONENT24, size, size);
                                            ^
release/CMakeFiles/raylib.dir/build.make:230: recipe for target 'release/CMakeFiles/raylib.dir/rlgl.c.o' failed
make[2]: *** [release/CMakeFiles/raylib.dir/rlgl.c.o] Error 1
make[2]: Target 'release/CMakeFiles/raylib.dir/build' not remade because of errors.
CMakeFiles/Makefile2:85: recipe for target 'release/CMakeFiles/raylib.dir/all' failed
make[1]: *** [release/CMakeFiles/raylib.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
make: Target 'default_target' not remade because of errors.
```

**Comment by raysan5** [comment]
ok, I see, thanks for reporting, some OpenGL 3.3 flags not supported in OpenGL ES 2.0...

**Comment by raysan5** [comment]
Just skipped problematic parts on commit https://github.com/raysan5/raylib/commit/2a263f7b5f6110dbcbfe8c5cc1be23d17fe534b6

No HDR environment maps on OpenGL ES 2.0 for the moment...

**Comment by define-private-public** [comment]
Well, it does compile now, but now there are linking issues on Linux...

```
../../release/libraylib.a(rlgl.c.o): In function `rlglInit':
rlgl.c:(.text+0x1f39): undefined reference to `eglGetProcAddress'
rlgl.c:(.text+0x1f4a): undefined reference to `eglGetProcAddress'
rlgl.c:(.text+0x1f5b): undefined reference to `eglGetProcAddress'
```

I tried some of the suggestions here but I didn't get that far: https://askubuntu.com/questions/244133/how-do-i-get-egl-and-opengles-libraries-for-ubuntu-running-on-virtualbox

The only thing different in my environment is that I'm using AMD's proprietary drivers on my desktop, I'll try later on my laptop which isn't "infected," but I doubt that I'll better results.  This might be fine enough for me try try Android compilation or Web compilation.

**Comment by raysan5** [comment]
OpenGL ES 2.0 shouldn't compile on Linux... it's intended only for Android, RPI and Web.

Well, actually, it can also work on desktops if `GLX_EXT_create_context_es2_profile` extension is supported and everything is properly configured... but raylib it's not prepared for that case... it will imply some redesign... not that big... maybe I can consider that option...

One interesting article on that point: https://www.g-truc.net/post-0457.html

**Comment by define-private-public** [comment]
Huh.  I've been able compile and run OpenGL ES 2.0 apps before on desktop Linux.  Might be able to just link mesa then...

**Comment by define-private-public** [comment]
Reporting that this happens on OS X If I try to build with OpenGL ES 2.0:

```
/Users/ben/Projects/raylib/src/rlgl.c:100:14: fatal error: 'EGL/egl.h' file not
      found
    #include <EGL/egl.h>            // EGL library
             ^
```

Until there is a better solution, I think it might be best just to disable GL ES 2.0 on the `Desktop` platform until there is a better solution for this `EGL` thing.  What should be the default version then?  I'm throwing my support in for 3.3 since it's the most up to date.

**Comment by raysan5** [comment]
Here more info on OpenGL versions support by platforms: https://github.com/raysan5/raylib/wiki/OpenGL-Graphic-API

Connection between OpenGL and the underlying native platform (Windows, Linux, OSX) is made using some system specific libraries (WGL, GLX, CGL) while [EGL](https://en.wikipedia.org/wiki/EGL_(API)) is used by some other specific platforms (Android, RaspberryPi).

**Comment by define-private-public** [comment]
Yeah, I think it might be better to disable GL ES 2.0 for desktop platforms for the moment.  Shall I default it to 3.3?

**Comment by raysan5** [comment]
Yes, it's ok to default to 3.3 on desktop platforms.

**Comment by raysan5** [comment]
Just closing this issue, OpenGL ES 2.0 support has already been discussed.
