### PR TITLE
Fix build.zig

### PR DESCRIPTION
**Pull request by cedeon**
I can only get zig to build raylib if I do this + move the file to the parent directory.

### CODE REVIEW

**Comment by CrackedPixel** [comment]
> I can only get zig to build raylib if I do this + move the file to the parent directory.

1) Did you get the latest changes from master branch? 
2) What platform are you building on?
3) Is the issue building or using it after building?

I tried this and it worked perfectly (linux x64, zig 0.13.0):
```
git clone git@github.com:raysan5/raylib.git
cd raylib
zig build
```

**Comment by sagehane** [comment]
I'm having the same issues with the latest commit on Linux, using the `addRaylib` function with the Zig package manager.

Seems to be introduced by https://github.com/raysan5/raylib/pull/4358 where it caused a mismatch between the fields of `Options` and the expected fields inside the logic of `addRaylib`.
https://github.com/raysan5/raylib/blob/4050b55055f0e545a032a51a5c1e66edba7b016c/src/build.zig#L27
https://github.com/raysan5/raylib/blob/4050b55055f0e545a032a51a5c1e66edba7b016c/src/build.zig#L300

**Comment by sagehane** [comment]
How to reproduce:
1. Start a new Zig project with `zig init`.
2. Add a sufficiently new version of Raylib as a dependency with `zig fetch --save=raylib https://github.com/raysan5/raylib/archive/3fb1ba25aca0a6b023ca254a0910df36b0744e64.tar.gz`
3. Add the following lines inside the `build` function of `build.zig`:
```zig
    const raylib = @import("raylib");
    const raylib_lib = try raylib.addRaylib(b, target, optimize, .{});
```
4. Run `zig build` to get the following output:
```sh-session
$ zig build
/home/<user>/.cache/zig/p/12207c7d223c949e1bdfbb2a789770427e0c61d4c288ef0e8935b1dc52ac2f82f807/src/build.zig:27:33: error: no field named 'platform_drm' in struct 'src.build.Options'
        .platform_drm = options.platform_drm,
                                ^~~~~~~~~~~~
/home/<user>/.cache/zig/p/12207c7d223c949e1bdfbb2a789770427e0c61d4c288ef0e8935b1dc52ac2f82f807/src/build.zig:294:21: note: struct declared here
pub const Options = struct {
                    ^~~~~~
referenced by:
    build: /home/<user>/Projects/mario/build.zig:33:44
    runBuild__anon_5106: /nix/store/h4xqfb0ganmpwzrzpbnxmhvy74r9hwfd-zig-0.14.0-dev.1823+b00cbecfd/lib/std/Build.zig:2294:33
    6 reference(s) hidden; use '-freference-trace=8' to see all references
```

**Comment by sagehane** [comment]
I also needed the following patch to get it building:
```diff
diff --git a/src/build.zig b/src/build.zig
index d79fb0f3..fef4893c 100644
--- a/src/build.zig
+++ b/src/build.zig
@@ -24,11 +24,11 @@ pub fn addRaylib(b: *std.Build, target: std.Build.ResolvedTarget, optimize: std.
         .rshapes = options.rshapes,
         .rtext = options.rtext,
         .rtextures = options.rtextures,
-        .platform_drm = options.platform_drm,
+        .platform = options.platform,
         .shared = options.shared,
         .linux_display_backend = options.linux_display_backend,
         .opengl_version = options.opengl_version,
-        .config = options.config,
+        .config = options.config orelse "",
     });
     const raylib = raylib_dep.artifact("raylib");
 
@@ -366,7 +366,7 @@ pub fn build(b: *std.Build) !void {
         .shared = b.option(bool, "shared", "Compile as shared library") orelse defaults.shared,
         .linux_display_backend = b.option(LinuxDisplayBackend, "linux_display_backend", "Linux display backend to use") orelse defaults.linux_display_backend,
         .opengl_version = b.option(OpenglVersion, "opengl_version", "OpenGL version to use") orelse defaults.opengl_version,
-        .config = b.option([]const u8, "config", "Compile with custom define macros overriding config.h") orelse null,
+        .config = b.option([]const u8, "config", "Compile with custom define macros overriding config.h"),
     };
 
     const lib = try compileRaylib(b, target, optimize, options);
```

The `orelse null` is redundant so I removed that. It seems like `b.dependencyFromBuildZig` doesn't support `?[]const u8` (the type of `options.config`) so I had to change it to `orelse ""`. I have no idea if this approach is correct though.

**Comment by raysan5** [comment]
@cedeon @CrackedPixel @sagehane Thanks for reporting! Please note that I don't maintain the `build.zig` so I usually trust Zig experienced users sending PRs.
