### ISSUE TITLE
[build] Failed to compile on Linux Desktop with OpenGL ES 2.0

### ISSUE THREAD

**Issue by zertyz** [raysan5/raylib#1183]
Hi, ray.

I just cloned the sources and was trying to compile it on a very old budget "netbook" laptop capable only of opengles2, running archlinux (updated today):

# cd src; make clean; make PLATFORM=PLATFORM_DESKTOP GRAPHICS=GRAPHICS_API_OPENGL_ES2
rm -fv *.o /home/luiz/tmp/git/raylib/src/libraylib.a /home/luiz/tmp/git/raylib/src/libraylib.bc /home/luiz/tmp/git/raylib/src/libraylib.so*
removed all generated files!
gcc -c core.c -Wall -D_DEFAULT_SOURCE -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing -std=c99 -fPIC -s -O1 -Werror=implicit-function-declaration -I. -Iexternal/glfw/include -Iexternal/glfw/deps/mingw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_ES2
In file included from /usr/include/X11/Xlib.h:44,
                 from /usr/include/EGL/eglplatform.h:128,
                 from /usr/include/EGL/egl.h:39,
                 from rlgl.h:666,
                 from core.c:136:
/usr/include/X11/X.h:100:13: error: conflicting types for ‘Font’
  100 | typedef XID Font;
      |             ^~~~
In file included from core.c:116:
raylib.h:284:3: note: previous declaration of ‘Font’ was here
  284 | } Font;
      |   ^~~~
make: *** [Makefile:520: core.o] Error 1

**Comment by raysan5** [comment]
@zertyz I'm afraid that specific configuration is [not supported by default](https://github.com/raysan5/raylib/wiki/raylib-platforms-and-graphics).

Did you try with `GRAPHICS_API_OPENGL11` or `GRAPHICS_API_OPENGL21`? Considering you are compiling for desktop platform, those backends should probably be emulated by mesa drivers.

It's also a bit weird `Font` symbol conflict, it didn't happen on any other `OpenGL ES 2.0` platform...

**Comment by zertyz** [comment]
opengl 21 and 11 fails with:
WARNING: [GLFW3 Error] Code: 65543 Decription: GLX: Failed to create context: GLXBadFBConfig
WARNING: GLFW Failed to initialize Window
‘./models_animation’ terminated by signal 11

**Comment by raysan5** [comment]
@zertyz sorry, I can't do more here, this is a specific configuration not supported at the moment.

**Comment by chriscamacho** [comment]
i know this is a year old but I have something pertinent

I've been able to run raylib with GLES by using PLATFORM_DRM

no joy at all with nvidia driver but both nouveau and intel drivers working fine - but then I'm about done with proprietary blobs

This could open the way for custom "consoles" mini OS projects, all based on just a slimmed down Linux kernel...

It runs without root (no need for sudo - not a great idea anyhow) and will run alongside a running X11 session as long as you start it from a "real" terminal (alt-f1)

**Comment by colesnicov** [comment]
Hi. I'll also try compiling with the following settings:

```
PLATFORM=DESKTOP
GRAPHICS=ES2
```

But it will come down to compiling samples with this announcement:

```
denis@raspberrypi:~/dev/raylib/build $ make -j4
[ 11%] Built target glfw
[ 11%] Building C object raylib/CMakeFiles/raylib.dir/rcore.c.o
[ 11%] Building C object raylib/CMakeFiles/raylib.dir/raudio.c.o
[ 11%] Building C object raylib/CMakeFiles/raylib.dir/rmodels.c.o
[ 12%] Building C object raylib/CMakeFiles/raylib.dir/rshapes.c.o
<command-line>: warning: "MAX_MESH_VERTEX_BUFFERS" redefined
<command-line>: note: this is the location of the previous definition
<command-line>: warning: "MAX_MESH_VERTEX_BUFFERS" redefined
<command-line>: note: this is the location of the previous definition
<command-line>: warning: "MAX_MESH_VERTEX_BUFFERS" redefined
<command-line>: note: this is the location of the previous definition
<command-line>: warning: "MAX_MESH_VERTEX_BUFFERS" redefined
<command-line>: note: this is the location of the previous definition
[ 12%] Building C object raylib/CMakeFiles/raylib.dir/rtext.c.o
<command-line>: warning: "MAX_MESH_VERTEX_BUFFERS" redefined
<command-line>: note: this is the location of the previous definition
[ 12%] Building C object raylib/CMakeFiles/raylib.dir/rtextures.c.o
<command-line>: warning: "MAX_MESH_VERTEX_BUFFERS" redefined
<command-line>: note: this is the location of the previous definition
[ 12%] Building C object raylib/CMakeFiles/raylib.dir/utils.c.o
<command-line>: warning: "MAX_MESH_VERTEX_BUFFERS" redefined
<command-line>: note: this is the location of the previous definition
[ 13%] Linking C static library libraylib.a
[ 13%] Built target raylib
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libOpenGL.so', needed by 'examples/audio_music_stream'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libOpenGL.so', needed by 'examples/audio_module_playing'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libOpenGL.so', needed by 'examples/audio_mixed_processor'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libOpenGL.so', needed by 'examples/audio_raw_stream'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 13%] Building C object examples/CMakeFiles/audio_mixed_processor.dir/audio/audio_mixed_processor.c.o
[ 13%] Building C object examples/CMakeFiles/audio_module_playing.dir/audio/audio_module_playing.c.o
[ 13%] Building C object examples/CMakeFiles/audio_music_stream.dir/audio/audio_music_stream.c.o
[ 13%] Building C object examples/CMakeFiles/audio_raw_stream.dir/audio/audio_raw_stream.c.o
make[1]: *** [CMakeFiles/Makefile2:613: examples/CMakeFiles/audio_music_stream.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:586: examples/CMakeFiles/audio_module_playing.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:559: examples/CMakeFiles/audio_mixed_processor.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:640: examples/CMakeFiles/audio_raw_stream.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```


Yes, I'm **trying to compile on RPI** 2B. I have wayland compositor installed so in `cmake` I choose `GLFW > ​​Wayland`..

I don't want X11 support. But I need to compile the project so that it opens a normal GLFW window but under the OpenGL ES2 briefcase.   

**RayLib itself compiles, the compilation of the examples fails, but I need them to measure performance.**
