### ISSUE TITLE
[rtexture] Failing Android build after changing to stb_image_resize2.h

### ISSUE THREAD

**Issue by M374LX** [raysan5/raylib#3491]
### Issue description

When trying to build for Android with Gradle after #3403 was merged, it fails with errors like:

``
error: initializing 'float16x8_t' (vector of 8 'float16_t' values) with an expression of incompatible type 'int'
C/C++:     float16x8_t in = vld1q_f16(input);
C/C++:                 ^    ~~~~~~~~~~~~~~~~
``

as well as warnings like:

``
warning: implicit declaration of function 'vcvt_f32_f16' is invalid in C99 [-Wimplicit-function-declaration]
C/C++:     return vgetq_lane_f32(vcvt_f32_f16(vdup_n_f16(h)), 0);
C/C++:                           ^
``

I am using an older version of the Android project template from https://github.com/Bigfoot71/Raymob.

### Environment

Linux

**Comment by jestarray** [comment]
I remember someone having a similar issue in the discord. On a different note, I just followed the wiki on  how to build for android and it worked fine with 5.0 bindings.

**Comment by raysan5** [comment]
@Bigfoot71 I think you faced a similar issue but it finally worked, right?

**Comment by Bigfoot71** [comment]
> @Bigfoot71 I think you faced a similar issue but it finally worked, right?

Yes, here's how I was able to resolve the issue with [CMake](https://github.com/Bigfoot71/Raymob/blob/4.6-dev/app/src/main/cpp/deps/raylib/CMakeLists.txt#L27-L31) in Android Studio:
```cmake
if(CMAKE_ANDROID_ARCH_ABI STREQUAL "armeabi-v7a")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mfloat-abi=softfp -mfpu=vfpv3-d16")
elseif(CMAKE_ANDROID_ARCH_ABI STREQUAL "arm64-v8a")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mfix-cortex-a53-835769")
endif()
```

And here's how it's done in the [Makefile](https://github.com/raysan5/raylib/blob/master/src/Makefile#L361-L366) of raylib:
```make
ifeq ($(ANDROID_ARCH),arm)
    CFLAGS += -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16
endif
ifeq ($(ANDROID_ARCH),arm64)
    CFLAGS += -target aarch64 -mfix-cortex-a53-835769
endif
```
